spring.profiles.wsUri=ws://211.149.137.58:7397

server.port=8078
# https配置 测试环境不需要
#server.ssl.key-store=keystore.p12
#server.ssl.key-store-password=182937
#server.ssl.keyStoreType=PKCS12
#server.ssl.keyAlias=tomcat
# websocket端口
server.websocket.port=7397

server.ssl.websocket.port=7397
logging.level.root=DEBUG
log.path=/opt/logs/icars/logs
spring.datasource.url=jdbc:mysql://47.109.195.116:3306/icars?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
spring.datasource.username=root
spring.datasource.password=Amiba123
spring.datasource.filters=wall,mergeStat
spring.wx.videoLocalPath=/home/ftpuser/www/video/
spring.wx.videoHost=http://211.149.137.58:8079/video/
spring.wx.netHost=http://211.149.137.58:8079/
spring.wx.claimImgLocalPath=/home/ftpuser/www/claimImg/
spring.wxpay.appid=wxda3db78c8532c5fd
spring.wxpay.mchid=1487083832
spring.wxpay.key=jdfjdfd7365uyilz8765rtd6d6c6g7g3
spring.wxpay.certPath=/opt/deploy/apiclient_cert.p12
spring.wxpay.notify-url=http://sssddd.free.idcfengye.com/api/v1/wxpay/notify
spring.system.headimgHost=http://211.149.137.58:8078/claimImg/headImg/
spring.system.file-upload-path=/home/ftpuser/www/claimImg/headImg/
# redis 密码
redis.auth=123456
redis.host=127.0.0.1