server.port=8082
spring.profiles.active=local

wx.appId=wx5d88d6c7c216e1f3
wx.secret=5a270b0335035e06504896e57f369f2e
wx.grantType=authorization_code
wx.sessionHost=https://api.weixin.qq.com/sns/jscode2session
alipay.appid=2018071960670475
alipay.publickey=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtoC3dzpnS0bXjtfmBLUaK/87Q8fOJ5e8oMoHUkZSkro6KeLs9ARcbxsO1uZ3mATe/JQp4XFLxQG2UJLWinrleEfwPImPVvLi/0PqqwWR81I4uG72obQsMGLjy2dBoDmdj55+/QfjPg/0amOFEV2+9GOLs/U2xQpFA28F8SDJm1pKgg4jKIHItSR/M4JK4bZ+HrXOtm9fblY2HsEASBCft5mQ+3FgfPHHMXk7uSXlBbHW1H4MAAgoG+H7zPwu9xtTdbA6Td22TMte666oblniyHApo9STmOxUgY3dDB7agr5rEOtZAP1xF3Eup6g6wmgeq4bqiF6/62+ZcqL4VfuBqQIDAQAB
alipay.privatekey=MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCYgAmcWH6WmfB7OK/m7TMG+e0CMrU2CkaQOAHIaaVj4vuNUCNnujkEdVl3X2GX6HaYjijqgfsiQNsW85BABn4ZGhOvmKtINhhRY6wTejZGPQjuLcD351ZlpVrvk2BkF0H4i5xi4Cgq7n0blmLAYQNQpUKtn7eKOd7Nvt+z+RTX2RxDrYk3KF3TCTe367U1zqqxVVqPbRqATe8YQABGdPOj6FCZ0qhKx00qR7+XIgZ94l9PjUVDv+ovaZFXt60u9RbeBebxJDwvJ4aQjOiOeVVGLjQ3K7mFQ9lzsMgss+a3wJJtE/P+wo6IvIDYqrWs+shQ3QTed3O4s7yxxKOF9UWRAgMBAAECggEAEkE5ZUq+lH6G5+koPUdllU8zjNDPGlHuknLx27CxyJwyKn9OTatgCeWWORDk2M9N6wMRaMj4a+hBkaTEPrXIQG77rkhjMHixPoTk40v81TmXKRO3BrXdhLtfgFAu+KxEDGGB7eARTtpPhY7h8U9rmyq9KZV13gkBX7Wah6uoUBIP05GqOiuZUvpc6onqVvae4z+1ZwkNRpX2f16Og7SYbs3AMh+xjOWCOrgtPrXmiVK+WUvwvMdX5DMlpeLXdGCewj240V1Z8Gvit1cBM1Rqaamh1hBtqA93FTQAqYyFq6eDKkSIx4/g+dYBHYvzK+oeORhFVbjYWAL1/9xtkC3GNQKBgQDzugPxp2eSJ66A6Dv9BHhZpwN4GefN0Kn30cANae6ibJLLIA8IGKMolqWe4vqLx+JuLCwL3kvsdyBGJsx3YaQVWNZCy138BUyj9bnUX6X5CVYov/GELC5/P+FHmt9buFJ/BO90DWngEqmwANrcWsRiNGtXdjX4aM6LnaZjTXWl/wKBgQCgLfuBcTcJ6bExafHNxD+1D/p5ZD5Qc1xmkroaZzVJb8gok2JTuCCU9GhFnU6QkTbOtbnaLz+P1FDvQ9RbQbaV766cgj+qUtjKzvrfX34qeI852Jfnmh2SLXHJa2Io5kO5nCsOrE7Gv7miKTHR81+slv6iecX/xWThn/dOhsW0bwKBgQC9yZbyoTIUbJQFS1ITN1zkKxqXdky8RwVjtdCAYYHytuskA2XRHyZGH/D+Ja+GE3Nt6TWvVD3499aI6gOD3uOfv9qwjp4z9oh0kI9RId4ja7LM7pKKIsFeU4cAdEgDqyeKQ3SXAS71znKWXEQRHRkZg8omhCWIt0xHCc8cOqAnTwKBgE6UACuR9KQiRlCtXnfI7E/QlNl0ObWRwiR3mmBVfSiXc6OkGbpkO2eXNofgEaiN9EsXjyLfxtiyGTonFkfmRsHrIMeahczyc3OaciueVvBS0EBaZrqxOgx5yrY6vZ6+xz6Iw/6gvMx3RYOtnckXETpDoIroHh/JICInLVUSfG51AoGBAMAt0YQdds6bO4HFM6Fu2RBLFS6pEi5Uze+Xio/6ije3VQJVUEEQKC/WvtSMtIV9R7L1gb/1GxnPPBAujFZkp6CZRSbTqX/F8InzvHLZz301me36AAGmxH06izxBfzns+KEGLh+DP6pdRPbPh2ZpPw1DQtJPqwyza6tkMF46oJod
alipay.gateway=https://openapi.alipay.com/gateway.do
# �Ƿ���swagger (true/false)
guns.swagger-open=true
# �Ƿ�����¼ʱ��֤�� (true/false)
guns.kaptcha-open=false
#  file-upload-path=/home/ftpuser/www/claimImg/headImg       #�ļ��ϴ�Ŀ¼(�����õĻ�Ϊjava.io.tmpdirĿ¼)
#�Ƿ���spring session,����Ƕ��������Ҫ����(true/false)
guns.spring-session-open=false
#sessionʧЧʱ��(ֻ�ڵ�����������Ч�����������SpringSessionConfig��������) ��λ����
guns.session-invalidate-time=86400
#��ü��һ��ʧЧ��session(ֻ�ڵ�����������Ч) ��λ����
guns.session-validation-interval=5
spring.mvc.static-path-pattern=/static/**
spring.mvc.view.prefix=/WEB-INF/view
spring.devtools.restart.enabled=false
spring.devtools.restart.additional-paths=src/main/java
spring.devtools.restart.exclude=static/**,WEB-INF/view/**
spring.servlet.multipart.max-request-size=100MB
spring.servlet.multipart.max-file-size=100MB
spring.mail.host=smtp.qq.com
spring.mail.username=2360500297@163.com
spring.mail.password=duanhong456
#spring.mail.properties.mail.smtp.socketFactory.class=javax.net.ssl.SSLSocketFactory
#spring.mail.properties.mail.smtp.socketFactory.port=465
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true
#spring.mail.properties.mail.smtp.starttls.required=true
mybatis-plus.typeAliasesPackage=com.stylefeng.guns.modular.system.model
mybatis-plus.configuration.log-impl=org.apache.ibatis.logging.slf4j.Slf4jImpl

#wx.pay.appId=wx580effc9532bd2a6
wx.pay.appId=wx580effc9532bd2a6
#wx.pay.appId=wxffaa8a6e1811c597
wx.pay.mchId=1742273656
wx.pay.mchKey=jdfjdfd7365uyilz8765rtd6d6c6g7g3