spring.profiles.wsUri=wss://chejiqiche.com/wss

server.port=8078

# https≈‰÷√
server.ssl.key-store=keystore.p12
server.ssl.key-store-password=182937
server.ssl.keyStoreType=PKCS12
server.ssl.keyAlias=tomcat

# websocket∂Àø⁄
server.websocket.port=7397

logging.level.root=DEBUG

server.servlet.context-path=/wx-admin
spring.application.name=wx-admin
log.path=/opt/logs/icars/logs

spring.datasource.url=jdbc:mysql://47.109.195.116:3306/icars?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
spring.datasource.username=root
spring.datasource.password=Amiba123
spring.datasource.db-name=icars
spring.datasource.filters=wall,mergeStat
spring.wx.videoLocalPath=/home/ftpuser/www/video/
spring.wx.videoHost=https://chejiqiche.com/video/
spring.wx.netHost=https://chejiqiche.com/
spring.wx.claimImgLocalPath=/home/ftpuser/www/claimImg/
spring.wxpay.appid=wxda3db78c8532c5fd
spring.wxpay.mchid=1487083832
spring.wxpay.key=jdfjdfd7365uyilz8765rtd6d6c6g7g3
spring.wxpay.certPath=/opt/deploy/apiclient_cert.p12
spring.wxpay.notify-url=https://www.chejiqiche.com/api/v1/wxpay/notify
spring.system.headimgHost=https://chejiqiche.com/claimImg/headImg/
spring.system.file-upload-path=/home/ftpuser/www/claimImg/headImg/

# redis √‹¬Î
redis.auth=Amiba123
redis.host=47.109.195.116