
server.port=8091
server.servlet.context-path=/bServer
spring.profiles.active=test

spring.mvc.view.prefix=classpath:/templates/
spring.mvc.view.suffix=.html
spring.thymeleaf.mode=LEGACYHTML5
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.cache=false


rocketmq.producer.isOnOff=on
rocketmq.producer.groupName=web
rocketmq.producer.namesrvAddr=127.0.0.1:9876
rocketmq.producer.maxMessageSize=4096
rocketmq.producer.sendMsgTimeout=3000
rocketmq.producer.retryTimesWhenSendFailed=2

