server.port=8083
server.servlet.context-path=/cServer
spring.profiles.active=test

spring.mvc.view.prefix=classpath:/templates/
spring.mvc.view.suffix=.html

#rocketmq.producer.isOnOff=on
#rocketmq.producer.groupName=web
#rocketmq.producer.namesrvAddr=127.0.0.1:9876
#rocketmq.producer.maxMessageSize=4096
#rocketmq.producer.sendMsgTimeout=3000
#rocketmq.producer.retryTimesWhenSendFailed=2

mybatis-plus.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl
spring.jackson.time-zone=GMT+8
#spring.jackson.date-format=yyyy-MM-dd HH:mm:ss

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

