-- 创建业务数据库
CREATE DATABASE IF NOT EXISTS `xxl_job` DEFAULT CHARACTER SET utf8mb4;
CREATE DATABASE IF NOT EXISTS `cheji` DEFAULT CHARACTER SET utf8mb4;
CREATE DATABASE IF NOT EXISTS `icars_test` DEFAULT CHARACTER SET utf8mb4;
CREATE DATABASE IF NOT EXISTS `icars_rest` DEFAULT CHARACTER SET utf8mb4;
CREATE DATABASE IF NOT EXISTS `jeesite` DEFAULT CHARACTER SET utf8mb4;
